name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: true
        repository: smatand/ifj2022
        token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}
    - name: update_submodules
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    
    - name: Commit
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions - update submodules"
        git add --all
        git commit -m "Update submodule by @galloj" || echo "No changes to commit"
        git push
      
    # scanner tests
    - name: scanner_tests
      run: |
        cd src
        make clean
        make scan_test
    # student tests
    - name: student_tests_by_galloj
      run: |
        cd src
        make clean
        make student_test
    # parser tests
