name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # scanner tests
    - name: scanner_tests
      run: |
        cd src
        make clean
        make scan_test
    # parser tests
